services:
  api:
    build:
      context: .              # your project root
      dockerfile: Dockerfile  # optional if named "Dockerfile"
    container_name: chaos-api
    ports:
      - "1323:8080"
    environment:
      - MONGODB_URI=mongodb://root:example@mongo:27017
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
